import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/header";
import { useAnimation, useScroll,motion, MotionValue } from "framer-motion"
import { useEffect, useState } from "react";
import Work from "../components/work";
const Home: NextPage = () => {
  const {scrollYProgress,scrollY}=useScroll()



const y=useAnimation()

const [top,setTop]=useState<number>(0)
const [progress,setProgress]=useState(0.4)
const [position,setPosition]=useState(0)


  useEffect(()=>{
   
    scrollY.onChange(()=>{
    if(scrollY.get()>500){
      setPosition(1)
    }
    else{
      setPosition(0)
    }
      if(scrollY.get()<320){
        if((scrollY.get()/320)>0.4&&(scrollY.get()/320)<1){
          setTop(scrollY.get())
          setProgress(scrollY.get()/320)

        }
       

      }

      if(scrollY.get()>360&&scrollY.get()<640){
        if(scrollY.get()<640){
          if(-1*(1-(640/scrollY.get()))>0.4){
            setProgress(-1*(0.12+1-(640/scrollY.get())))

          }
          
        }
      } 

      
    })
  },[scrollY.get()])






  return (
    <>
      <Head>
        <title>Hossem edine ali |Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[800px]   bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Header/>

        <div className="relative h-screen     ">
          <div className="w-full px-10 md:w-1/2 h-[200px] md:py-10 ">
                <p className="text-white text-xl md:text-2xl lg:text-3xl font-bold">Hi!</p>
                <p className="text-white text-xl md:text-2xl lg:text-3xl font-bold">I am Hossem edine ali</p>
                <p className="text-white text-xl md:text-2xl lg:text-3xl font-bold">A web developper</p>
          </div>
            {/*   */}
         {true&& <motion.div  style={{scale:`${+progress.toString()}` ,  } }

         className={` ${position==0?'fixed': 'absolute  '}   ${position==0?'top-0 right-0 left-0 bottom-0': 'top-[480px] right-0 left-0 bottom-[-380px]'}    z-10 border-2 ${progress>0.9?'overflow-auto':'overflow-hidden'} scrollbar-hide mt-10`}>
              <Work/>
          </motion.div>}
         
          {/*   <motion.div 
            
            className={`flex   md:hidden  border-2  max-w-full max-h-screen mx-auto ${top<269?'overflow-hidden':'overflow-scroll'}  scrollbar-hide ` }
            style={{top:top+350,width:(top+50)*2,height:(top+90)*2}}
            >
            {<Work/>}
            </motion.div> */}




            {/* <div          
              className={` md:flex   hidden  border-2  max-w-full max-h-screen mx-auto ${top<269?'overflow-hidden':'overflow-scroll'} scrollbar-hide` }
              style={{top:top+50,width:(top+300)*2,height:(top+90)*2}}
              >
                {<Work/>}
            </div> */}
            </div>
          <div className="h-[1500px] border-2 mt-[350px] bg-red-600">

        </div>
      </main>
    </>
  );
};

export default Home;